language: node_js
node_js:
  - lts/*
before_install: npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
script: 
  - npm run test
  - npm run build
after_script: greenkeeper-lockfile-upload
deploy:
  - provider: npm
    skip_cleanup: true
    email: mats.pfeiffer@googlemail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
cache: npm
notifications:
  email:
    on_success: never
    on_failure: always