language: node_js
node_js:
  - lts/*
install: npm install
script: 
  - npm run test
  - npm run build
deploy:
  - provider: npm
    skip_cleanup: true
    email: mats.pfeiffer@googlemail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
cache: npm
notifications:
  email:
    on_success: never
    on_failure: always