version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build